[package]
name = "user_stack"
version = "0.1.0"
edition = "2021"

[dependencies]
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
